### ISSUE TITLE
功能栏滚动条问题建议

### ISSUE THREAD

**Issue by nuyiy** [lyr613/novel-editer#1]
虽然我不写小说，但一直有关注 
说下我的体验吧
版本0.0.9
全屏模式到没什么问题，
退出全屏模式后的滚动条设置很不舒服，可以尝试设定一个最小范围，设定后，就没有滚动条，起码左侧功能栏不能有滚动条。

**Comment by lyr613** [comment]
> 虽然我不写小说，但一直有关注
> 说下我的体验吧
> 版本0.0.9
> 全屏模式到没什么问题，
> 退出全屏模式后的滚动条设置很不舒服，可以尝试设置一个最小范围，设置后，就没有滚动条，起码垂直功能栏不能有滚动条。

谢谢, 是最左侧的菜单吗, 因为我设置的是鼠标移入才会有滚动条, 不知道是不是系统兼容问题, 可以截图说明哪里吗. 916257973@qq.com或直接加我qq

**Comment by nuyiy** [comment]
是鼠标移入后才显示的。可以去掉或者再变细点

在 2020年6月27日星期六，lyr613 <notifications@github.com> 写道：

**Comment by lyr613** [comment]
哦哦因为我的眼睛不是很好，或许我会添加一个关于滚动条的配置，在做了在做了.jpg

**Comment by lyr613** [comment]
现在滚动条可以设置宽度和颜色
