### ISSUE TITLE
Cannot find module dll-build

### ISSUE THREAD

**Issue by GonHome** [lyr613/novel-editer#3]
当启动package中的view start时 报错
Cannot find module '/Users/xxxx/novel-editer/packages/view/dll-build/dll.manifest.json'
Require stack:
- /Users/xxxx/novel-editer/packages/view/config/webpack.config.js
- /Users/xxxx/novel-editer/packages/view/scripts/start.js

**Comment by lyr613** [comment]
抱歉忘了更新readme. 需要先执行setup-dll命令

GonHome <notifications@github.com> 于2020年8月25日周二 上午11:41写道：
